fs.delete("/srunix/kernel/shell.lua")
local content1 = http.get("https://raw.githubusercontent.com/Kvass134/srunix-utils/refs/heads/main/Corepatch/kernel/shell.lua")
local container1 = fs.open("/srunix/kernel/shell.lua", "w")
container1.write(content1.readAll())
content1.close()
container1.close()
local content2 = http.get("https://raw.githubusercontent.com/Kvass134/srunix-utils/refs/heads/main/Corepatch/kernel/compat.lua")
local container2 = fs.open("/srunix/compat.lua", "w")
container2.write(content2.readAll())
content2.close()
container2.close()
print("Patched!")
